2025-05-27 10:06:56,581 - root - ERROR - Error creating database tables: Foreign key associated with column 'user.created_by' could not find table 'users' with which to generate a foreign key to target column 'id'
2025-05-27 10:07:48,771 - root - ERROR - Error creating database tables: Foreign key associated with column 'user.modified_by' could not find table 'users' with which to generate a foreign key to target column 'id'
2025-06-05 07:40:40,637 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'media_files'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f3249325090>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 07:42:04,319 - app.db.session - ERROR - Database session error: app.models.article.Article() argument after ** must be a mapping, not ArticleCreate
2025-06-05 08:11:17,544 - app.db.session - ERROR - Database session error: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https://errors.pydantic.dev/2.11/v/model_attributes_type'}

2025-06-05 09:08:32,234 - app.db.session - ERROR - Database session error: 
2025-06-05 09:15:41,858 - app.db.session - ERROR - Database session error: 
2025-06-05 09:17:10,290 - app.db.session - ERROR - Database session error: 
2025-06-05 09:19:29,067 - app.db.session - ERROR - Database session error: 
2025-06-05 09:21:11,156 - app.db.session - ERROR - Database session error: 
2025-06-05 09:23:44,088 - app.db.session - ERROR - Database session error: 
2025-06-05 09:24:58,114 - app.db.session - ERROR - Database session error: object of type 'int' has no len()
2025-06-05 09:29:55,079 - app.db.session - ERROR - Database session error: (psycopg2.errors.UndefinedColumn) column "updated_at" of relation "media_file" does not exist
LINE 1: INSERT INTO media_file (filename, file_type, url, updated_at...
                                                          ^

[SQL: INSERT INTO media_file (filename, file_type, url, updated_at) VALUES (%(filename)s, %(file_type)s, %(url)s, %(updated_at)s) RETURNING media_file.id]
[parameters: {'filename': 'Screenshot (371).png', 'file_type': 'image/png', 'url': 'http://minio:9000/articles/b339352c-7c60-4ae4-9774-80b7010765bc.png', 'updated_at': datetime.datetime(2025, 6, 5, 9, 29, 55, 76915)}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-05 09:31:08,113 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ชื่อ-บทความ-สำหรับ-url) already exists.

[SQL: INSERT INTO article (title, slug, content, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ชื่อบทความ', 'slug': 'ชื่อ-บทความ-สำหรับ-url', 'content': 'เนื้อหาเริ่มต้น {{media_0}} ต่อเนื้อหา {{media_1}} จบเนื้อหา', 'created_at': datetime.datetime(2025, 6, 5, 9, 31, 8, 111378), 'updated_at': datetime.datetime(2025, 6, 5, 9, 31, 8, 111380)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-05 09:36:14,075 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'positions', 'int'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'list_type', 'loc': ('body', 'positions', 'list[int]'), 'msg': 'Input should be a valid list', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 09:37:05,671 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'positions', 'int'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'list_type', 'loc': ('body', 'positions', 'list[int]'), 'msg': 'Input should be a valid list', 'input': '"[0, 1]"', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 09:44:50,807 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'positions', 'int'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[0, 1]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}, {'type': 'list_type', 'loc': ('body', 'positions', 'list[int]'), 'msg': 'Input should be a valid list', 'input': '[0, 1]', 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-05 09:58:50,664 - app.db.session - ERROR - Database session error: 
2025-06-05 10:00:55,278 - app.db.session - ERROR - Database session error: 
2025-06-05 10:02:55,153 - app.db.session - ERROR - Database session error: 
2025-06-05 10:05:39,636 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-05 10:06:32,694 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-05 10:06:40,642 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-05 10:08:20,051 - app.db.session - ERROR - Database session error: 
2025-06-05 10:08:45,987 - app.db.session - ERROR - Database session error: 
2025-06-05 10:09:10,960 - app.db.session - ERROR - Database session error: 
2025-06-05 10:37:46,160 - app.db.session - ERROR - Database session error: 
2025-06-05 10:37:52,058 - app.db.session - ERROR - Database session error: 
2025-06-06 03:35:10,661 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:35:20,905 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:35:27,047 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:35:53,461 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:37:58,092 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:38:22,108 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:39:43,476 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:39:53,019 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 03:41:28,198 - app.db.session - ERROR - Database session error: [{'type': 'list_type', 'loc': ('body', 'media_files'), 'msg': 'Input should be a valid list', 'input': <starlette.datastructures.UploadFile object at 0x7f40c2966e50>, 'url': 'https://errors.pydantic.dev/2.11/v/list_type'}]
2025-06-06 03:44:43,880 - app.db.session - ERROR - Database session error: object of type 'UploadFile' has no len()
2025-06-06 03:48:24,208 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 03:48:27,751 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(ttttt2) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'tttt2', 'slug': 'ttttt2', 'content': 'tttt2', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 6, 3, 48, 27, 749768), 'updated_at': datetime.datetime(2025, 6, 6, 3, 48, 27, 749771)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-06 03:49:02,752 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 03:50:17,388 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 04:02:05,429 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 04:03:13,622 - app.db.session - ERROR - Database session error: 'UploadFile' object is not iterable
2025-06-06 04:04:51,527 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:07:26,604 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:08:39,186 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:08:53,904 - app.db.session - ERROR - Database session error: [{'type': 'value_error', 'loc': ('body', 'media_files', 0), 'msg': "Value error, Expected UploadFile, received: <class 'str'>", 'input': '', 'ctx': {'error': ValueError("Expected UploadFile, received: <class 'str'>")}, 'url': 'https://errors.pydantic.dev/2.11/v/value_error'}]
2025-06-06 04:10:47,135 - app.db.session - ERROR - Database session error: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "article_view_log" violates not-null constraint
DETAIL:  Failing row contains (1, 2, null, null, 172.24.0.1, 2025-06-06 04:10:47.128187).

[SQL: INSERT INTO article_view_log (article_id, user_id, user_session_id, ip_address, viewed_at) VALUES (%(article_id)s, %(user_id)s, %(user_session_id)s::UUID, %(ip_address)s, %(viewed_at)s) RETURNING article_view_log.id]
[parameters: {'article_id': 2, 'user_id': None, 'user_session_id': None, 'ip_address': '172.24.0.1', 'viewed_at': datetime.datetime(2025, 6, 6, 4, 10, 47, 128187)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-06 04:12:03,035 - app.db.session - ERROR - Database session error: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "article_view_log" violates not-null constraint
DETAIL:  Failing row contains (2, 2, null, null, 172.24.0.1, 2025-06-06 04:12:03.029236).

[SQL: INSERT INTO article_view_log (article_id, user_id, user_session_id, ip_address, viewed_at) VALUES (%(article_id)s, %(user_id)s, %(user_session_id)s::UUID, %(ip_address)s, %(viewed_at)s) RETURNING article_view_log.id]
[parameters: {'article_id': 2, 'user_id': None, 'user_session_id': None, 'ip_address': '172.24.0.1', 'viewed_at': datetime.datetime(2025, 6, 6, 4, 12, 3, 29236)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-06 04:22:10,325 - app.db.session - ERROR - Database session error: 
2025-06-06 04:22:24,974 - app.db.session - ERROR - Database session error: 
2025-06-09 10:47:37,221 - app.db.session - ERROR - Database session error: [{'type': 'missing', 'loc': ('body', 'category_ids'), 'msg': 'Field required', 'input': None, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}]
2025-06-09 10:48:28,678 - app.db.session - ERROR - Database session error: [{'type': 'missing', 'loc': ('body', 'category_ids'), 'msg': 'Field required', 'input': None, 'url': 'https://errors.pydantic.dev/2.11/v/missing'}]
2025-06-09 10:50:47,364 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 10:50:50,076 - app.db.session - ERROR - Database session error: 'NoneType' object is not iterable
2025-06-09 10:52:17,812 - app.db.session - ERROR - Database session error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "article_slug_key"
DETAIL:  Key (slug)=(gggggg) already exists.

[SQL: INSERT INTO article (title, slug, content, view_count, created_at, updated_at) VALUES (%(title)s, %(slug)s, %(content)s, %(view_count)s, %(created_at)s, %(updated_at)s) RETURNING article.id]
[parameters: {'title': 'ggggggg', 'slug': 'gggggg', 'content': 'gggggg', 'view_count': 0, 'created_at': datetime.datetime(2025, 6, 9, 10, 52, 17, 808955), 'updated_at': datetime.datetime(2025, 6, 9, 10, 52, 17, 808959)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-06-09 10:57:17,295 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 10:57:35,206 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '[1,2]', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 10:58:06,797 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 11:00:18,694 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
2025-06-09 11:00:33,773 - app.db.session - ERROR - Database session error: [{'type': 'int_parsing', 'loc': ('body', 'category_ids', 0), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': '1,2', 'url': 'https://errors.pydantic.dev/2.11/v/int_parsing'}]
